<div class="row">
	<div class="col-md-12 col-sm-12 zero-pad-all full-image the-truth base-text full-text border">
		<h2><strong>Sunbeds:</strong> The Truth</h2>
	</div>
</div>
<div class="row border">
	<div class="col-md-6 col-sm-6 col-xs-12 zero-pad-all half-image base-text half-text faketan border">
		<h2><strong>Fake Tanning Tips</strong></h2>
	</div>
	<div class="col-md-6 col-sm-6 col-xs-12 zero-pad-all half-image base-text half-text casestudies border">
		<h2><strong>Case Studies</strong></h2>
	</div>
</div>
<div class="row ">
	<div class="col-md-12 col-sm-12 zero-pad-all base-text full-text competition border">
		<h2 class="win-header-text"><strong>Win!</strong></h2>
		<div class="row">
			<div class="col-md-8 col-sm-8 zero-pad-all competition-text">
				A Year supply of St Morritz!&nbsp;&nbsp;<span class="facebook">Visit us on Facebook&nbsp;<a href="#"><img src="/siteElements/ChannelShift/content/images/sunbeds/Facebook.svg" alt="facebook sunbeds blackpool council" /></a></span>
			</div>
			<div class="col-md-4 col-sm-4 terms pull-right zero-pad-all">
				<a href="#">terms and conditions apply</a>
			</div>
		</div>
	</div>
</div>
