<script type="application/ld+json">
	{
"@context": "https://schema.org",
  "@type": "Organization",
  "url": "https://www.Blackpool.gov.uk",
  "name": "Main Navigation Menu",
  "potentialAction": [
    {
               "@type": "searchAction",
               "name": "Resident",
               "description": "Services available for Blackpool residents",
               "url": "https://www.blackpool.gov.uk/Residents/Residents.aspx"
    },
    {
               "@type": "searchAction",
               "name": "Business",
               "description": "Services, advice and help for businesses in Blackpool",
               "url": "https://www.blackpool.gov.uk/Business/Business.aspxe"
    },
    {
               "@type": "searchAction",
               "name": "The Council",
               "description": "Details on the democratic operation of Blackpool Council",
              "url": "https://www.blackpool.gov.uk/Your-Council/Your-Council.aspx"
    },
    {
               "@type": "searchAction",
               "name": "Visitors",
               "description": "Visit Blackpool website full of information on planning your visit to Blackpool",
               "url": "https://www.visitblackpool.com/"
    }
    ]
}

</script>

<script type="application/ld+json">
	{
"@context": "https://schema.org",
  "@type": "Organization",
  "url": "https://www.Blackpool.gov.uk",
  "name": "Residents Footer Links",
  "potentialAction": [
    {
               "@type": "Action",
               "name": "Advice and Support",
               "description": "Trading standard and food hygiene advice",
               "url": "https://www.blackpool.gov.uk/Residents/Advice-and-support/Advice-and-support.aspx"
    },
    {
               "@type": "Action",
               "name": "Benefits",
               "description": "Information on applying for benefits from Blackpool Council",
               "url": "https://www.blackpool.gov.uk/Residents/Benefits/Benefits.aspx"
    },
    {
               "@type": "Action",
               "name": "Blackpool Illuminations",
               "description": "History and times for Blackpools illuminations",
               "url": "https://www.blackpool.gov.uk/Residents/Blackpool-Illuminations/Blackpool-Illuminations.aspx"
    },
    {
               "@type": "Action",
               "name": "Council Tax",
               "description": "Details of your council tax including payments",
               "url": "https://www.blackpool.gov.uk/Residents/Council-tax/Council-Tax.aspx"
    },
    {
               "@type": "Action",
               "name": "Education and Schools",
               "description": "Information on schools and education in Blackpool",
               "url": "https://www.blackpool.gov.uk/Residents/Education-and-schools/Education-and-schools.aspx"
    }
    ,
    {
               "@type": "Action",
               "name": "Health and School Care",
               "description": "Blackpool social services and public health",
               "url": "https://www.blackpool.gov.uk/Residents/Health-and-social-care/Health-and-social-care.aspx"
    },
    {
               "@type": "Action",
               "name": "Housing",
               "description": "Information on social housing in Blackpool",
               "url": "https://www.blackpool.gov.uk/Residents/Housing/Housing.aspx"
    },
    {
               "@type": "Action",
               "name": "Libraries and Heritage",
               "description": "Information on Blackpool libraries and heritage collections",
               "url": "https://www.blackpool.gov.uk/Residents/Libraries-arts-and-heritage/Libraries-arts-and-heritage.aspx"
    },
    {
               "@type": "Action",
               "name": "Life Events",
               "description": "Registering a birth or death and getting married in Blackpool",
               "url": "https://www.blackpool.gov.uk/Residents/Life-events/Life-events.aspx"
    },
    {
               "@type": "Action",
               "name": "Parking Road and Transport",
               "description": "Information on parking or reporting road problems in Blackpool",
               "url": "https://www.blackpool.gov.uk/Residents/Parking-roads-and-transport/Parking-roads-and-transport.aspx"
    },
    {
               "@type": "Action",
               "name": "Parks and Community Facilities",
               "description": "Information on Blackpool parks and leisure facilities",
               "url": "https://www.blackpool.gov.uk/Residents/Parks-and-community-facilities/Parks-and-community-facilities.aspx"
    },
    {
               "@type": "Action",
               "name": "Planning Evnvironment and Community",
               "description": "Planning applications, building control and community activities",
               "url": "https://www.blackpool.gov.uk/Residents/Planning-environment-and-community/Environmental-and-community.aspx"
    },
    {
               "@type": "Action",
               "name": "Sport and Leisure",
               "description": "Information on sports and leisure centres",
               "url": "https://www.blackpool.gov.uk/Residents/Sports-and-leisure/Sport-Blackpool.aspx"
    },
    {
               "@type": "Action",
               "name": "Waste and Recycling",
               "description": "Information on bin collections and recycling",
               "url": "https://www.blackpool.gov.uk/Residents/Waste-and-recycling/Waste-and-recycling.aspx"
    }
    ]
}

</script>
<script type="application/ld+json">
	{
"@context": "https://schema.org",
  "@type": "Organization",
  "url": "https://www.Blackpool.gov.uk",
  "name": "Business Footer Links",
  "potentialAction": [
    {
               "@type": "Action",
               "name": "Business Rates",
               "description": "Information and advice on paying business rates",
               "url": "https://www.blackpool.gov.uk/Business/Business-rates/Business-rates.aspx"
    },
    {
               "@type": "Action",
               "name": "Business Support and Advice",
               "description": "Advise and help available to business owners",
               "url": "https://www.blackpool.gov.uk/Business/Business-support-and-advice/Business-support-and-advice.aspx"
    },
       {
               "@type": "Action",
               "name": "Commercial Waste",
               "description": "Blackpool Council commercial waste collection service",
               "url": "https://www.blackpool.gov.uk/Business/Commercial-waste/Commercial-waste.aspx"
    },
      {
               "@type": "Action",
               "name": "Food Hygiene",
               "description": "Food hygiene advice for operators ",
               "url": "https://www.blackpool.gov.uk/Business/Commercial-waste/Commercial-waste.aspx"
    },
    {
               "@type": "Action",
               "name": "Licensing and Permits",
               "description": "Apply for a licence or permit",
               "url": "https://www.blackpool.gov.uk/Business/Licensing-and-permits/Licensing.aspx"
    },
    {
               "@type": "Action",
               "name": "Residential Landlords",
               "description": "Advice for renting properties for landlords",
               "url": "https://www.blackpool.gov.uk/Business/Residential-landlords/Residential-landlords.aspx"
    },
     {
               "@type": "Action",
               "name": "Working with the Council",
               "description": "Information on working with Blackpool Council",
               "url": "https://www.blackpool.gov.uk/Business/Working-with-the-council/Working-with-the-council.aspx"
    }
    ]
}

</script>
<script type="application/ld+json">
	{
"@context": "https://schema.org",
  "@type": "Organization",
  "url": "https://www.Blackpool.gov.uk",
  "name": "Your Council Footer Links",
  "potentialAction": [
    {
               "@type": "Action",
               "name": "Blackpool Council Jobs",
               "description": "Jobs available at Blackpool Council",
               "url": "https://www.blackpool.gov.uk/Your-Council/Blackpool-Council-jobs/Blackpool-Council-Jobs.aspx"
    },
    {
               "@type": "Action",
               "name": "Citizenship",
               "description": "Advice on applying for British citizenship",
               "url": "https://www.blackpool.gov.uk/Your-Council/Citizenship/Citizenship.aspx"
    },
       {
               "@type": "Action",
               "name": "Community Rights",
               "description": "Information on community rights",
               "url": "https://www.blackpool.gov.uk/Your-Council/Community-rights/Community-rights.aspx"
    },
     {
               "@type": "Action",
               "name": "Council Meetings",
               "description": "Details of Blackpool Council meetings including dates agenda and minutes",
               "url": "https://www.blackpool.gov.uk/Your-Council/Council-meetings/Blackpool-Council-meetings.aspx"
    },
    {
               "@type": "Action",
               "name": "Creating a Better Blackpool",
               "description": "Information on developments and improvements in Blackpool",
               "url": "https://www.blackpool.gov.uk/Your-Council/Creating-a-better-Blackpool/Creating-a-better-Blackpool.aspx"
    },
       {
               "@type": "Action",
               "name": "Have Your Say",
               "description": "Information on communication your views to Blackpool Council",
               "url": "https://www.blackpool.gov.uk/Your-Council/Have-your-say/Have-your-say.aspx"
    }, {
               "@type": "Action",
               "name": "Statistics and Research",
               "description": "Information on statistics available on Blackpool",
               "url": "https://www.blackpool.gov.uk/Your-Council/Statistics-and-research/Statistics-and-research.aspx"
    },
    {
               "@type": "Action",
               "name": "The Council",
               "description": "Blackpool Council its councillors and senior management",
               "url": "https://www.blackpool.gov.uk/Your-Council/The-Council/The-Council.aspx"
    },
       {
               "@type": "Action",
               "name": "Transparency and Open Data",
               "description": "Blackpool Councils open data sets",
               "url": "https://www.blackpool.gov.uk/Your-Council/Transparency-and-open-data/Transparency-and-open-data.aspx"
    },
     {
               "@type": "Action",
               "name": "Voting and Elections",
               "description": "Details on registering to vote and your ward",
               "url": "https://www.blackpool.gov.uk/Your-Council/Voting-and-elections/Voting-and-elections.aspx"
    },
    {
               "@type": "Action",
               "name": "Your Councillors",
               "description": "Elected representatives of Blackpool Council",
               "url": "https://www.blackpool.gov.uk/Your-Council/Your-councillors/Your-councillors.aspx"
    }
    ]
}

</script>
