<script type="text/javascript" >
function InitialiseC4A() {
	/* Chat Tool */
	var Tool7 = new C4A.Tools(7); 
	C4A.Run('692356e7-1b83-42ab-8696-cac0bfc1829a');
}
</script>

<noscript><a href="https://www.click4assistance.co.uk/add-live-chat-software-click4assistance-uk" target="_blank" style="font-size:10px;position:fixed;bottom:2px;right:2px;">Click4Assistance UK Live Chat Software</a></noscript>

<script src="https://v4in1-si.click4assistance.co.uk/SI.js" type="text/javascript" defer="defer"></script>
