<style type='text/css'>
.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } 
.embed-container iframe, .embed-container object, 
.embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }
</style>
<div class='embed-container'>
<iframe src='https://www.google.com/maps/d/embed?mid=1qoCnuN32pGBvx4R0SUAraavuJJVppII&ehbc=2E312F' width='640' height='480'></iframe>
</div>